services:
  mongo:
    image: mongo:4.0.4
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/data:/data/db
    restart: always

  client:
    image: helpdesk-client
    ports:
      - '4000:3000'

  server:
    image: helpdesk-server
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    volumes:
      - ./server:/app
    command: npm run start:dev
