services:
  mongo:
    image: mongo:4.0.4
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/data:/data/db
    restart: always

  frontend:
    build:
      context: ./client/frontend
      dockerfile: Dockerfile
      target: builder
    ports:
      - '4000:3000'
    volumes:
      - ./client/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  server:
    image: helpdesk-server
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    volumes:
      - ./server:/app
    command: npm run start:dev
