name: CI Build

on:
  push:
    branches:
      - main
    paths:
      - 'client/frontend/**'
      - 'server/**'
  pull_request:
    branches:
      - main
    paths:
      - 'client/frontend/**'
      - 'server/**'

jobs:
  client:
    runs-on: ubuntu-latest
    container:
      image: node:23-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.5.0'

      - name: Install dependencies
        working-directory: ./client/frontend
        run: |
          npm install

      - name: Run Jest tests
        working-directory: ./client/frontend
        run: |
          npm test

  server:
    runs-on: ubuntu-latest
    container:
      image: node:23-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.5.0'

      - name: Install dependencies
        working-directory: ./server
        run: |
          npm install

      - name: Run Jest tests
        working-directory: ./server
        run: |
          npm test
