name: CI Build

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
  pull_request:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  client:
    runs-on: ubuntu-latest
    container:
      image: node:16-slim # Utilisation de l'image Node.js pour les tests React/Next.js
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./client # Répertoire où se trouve ton projet Next.js
        run: |
          npm install

      - name: Run Jest tests
        working-directory: ./client # Répertoire où se trouve ton projet Next.js
        run: |
          npm test
